<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\MyWineCellar.Data\MyWineCellar.Data.csproj" />
    <ProjectReference Include="..\MyWineCellar.Models\MyWineCellar.Models.csproj" />
  </ItemGroup>

</Project>
